theme: jekyll-theme-minimal
title: OPORA
description: Tools for election data and disinformation monitoring
logo: https://en.wikipedia.org/wiki/NAFO_(group)#/media/File:NAFO_OFAN_brain_damaged_cartoon_dogs.jpeg
show_downloads: false
