theme: jekyll-theme-minimal
title: OEDvDISINFO
description: Election Data and Disinfo Monitoring Tools
logo: https://danivyboriv.net/wp-content/uploads/2022/11/canary_racoon-scaled.jpg
show_downloads: false
