theme: jekyll-theme-minimal
title: OPORA
description: Tools for election data and disinformation monitoring
logo: https://danivyboriv.net/wp-content/uploads/2022/11/canary_racoon-scaled.jpg
show_downloads: false
